### ISSUE TITLE
Support to Firebird 3.0

### ISSUE THREAD

**Issue by edgardmessias** [edgardmessias/yii2-firebird#3]
Add support to Firebird 3.0

**Comment by edgardmessias** [comment]
Current error:

``` sql
INSERT INTO animal (type) VALUES ('yiiunit\data\ar\Cat') RETURNING id
```

Error message:
`SQLSTATE[HY000]: General error: -902 Dynamic SQL Error SQLDA error Wrong number of parameters (expected 1, got 0)`

**Comment by edgardmessias** [comment]
@mariuz you can help me with this error?

https://travis-ci.org/edgardmessias/yii2-firebird/jobs/125567263

**Comment by edgardmessias** [comment]
@mariuz, I make test with interbase extension and works correctly with firebird 3.0

**Comment by edgardmessias** [comment]
https://bugs.php.net/bug.php?id=72931

**Comment by edgardmessias** [comment]
Waiting for php/php-src#2230

**Comment by mariuz** [comment]
Merged , please test

**Comment by mariuz** [comment]
@edgardmessias  Could you also test bool support ? 

https://github.com/php/php-src/pull/2522

**Comment by edgardmessias** [comment]
Waiting for https://travis-ci.org/edgardmessias/yii2-firebird/builds/222898726

**Comment by edgardmessias** [comment]
Updated yii2-firebird

Waiting for https://travis-ci.org/edgardmessias/yii2-firebird/builds/233350039

**Comment by mariuz** [comment]
I guess it can be closed

**Comment by razvanphp** [comment]
README states "Partial support with Firebird 3.0"

Is this still true? What is missing?

**Comment by mariuz** [comment]
@razvanphp 

Firebird 3.0 support for pdo was merged in previous versions of php , so on the yii2-firebird side the above bugs were fixed at that time (this why it was closed)

One fork that has php 8.x patch is here 

https://github.com/art009/yii2-firebird/commit/f432c7dc3861affe3777132635b367be525da202

There were more improvements in php 8.4 on the pdo firebird side (firebird 4.x and firebird5)

https://www.firebirdsql.org/en/news/php-8-4-improvements-when-working-with-modern-firebird-versions

**Comment by razvanphp** [comment]
Thanks for the links, hopefully @art009 can push the changes in a PR here.

Otherwise, what else is needed? I want to install this lib in production for connecting a legacy system for migrations.

**Comment by art009** [comment]
@razvanphp 
No problem, just a request to check for correctness, I made this patch a long time ago and don’t remember all the details.

**Comment by razvanphp** [comment]
I can add github actions with matrix for php versions to run the unit tests, if we still have someone with admin access to this repo to approve our MRs.

**Comment by art009** [comment]
This would be good, but I don't have the rights to admin this repo.

**Comment by razvanphp** [comment]
Let's create the PRs, I see @edgardmessias is still active on github, hopefully he can approve amd merge them or give us maintainer access for the future. Thanks!

**Comment by edgardmessias** [comment]
Yes, I am here and I can approve and merge the PR with some quality
